# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=6

systemProp.file.encoding=utf-8

group=me.srrrapero720

#########################
#### Mod properties ####
#######################
modid=waterframes
modname=WaterFrames
modbrandname=WATERFrAMES
modversion=2.1.22
modauthor=SrRapero720
modcredits=Models by FabiAcr and J-RAP. Textures by Kotyarendj
modlicense=All-Rights-Reserved
mod_description=Display custom video and pictures in your world.

####################
#### Mod pages ####
##################
curseforgeid=834607
modrinthid=eBzFuVTM
versiontype=release

#####################
#### Enviroment ####
###################
modloader=FABRIC
mcversion=1.21.8
mcrange=[1.21.8,1.21.9)
flversion=0.17.2
fabricversion=0.136.1+1.21.8
fgrange=[47,48)
mappings_channel=parchment
parchment_mcversion=1.21.5
mappings_version=2025.06.15
respack_version=64

#######################
#### Dependencies ####
#####################
watermediaversion=2.1.34
watermediarange=>=2.1.34

creativecoreversion=7048488
creativecorerange=>=2.14.7

watervisionversion=7022261
watervisionrange=>=0.1

#######################
#### Placeholders ####
#####################
mixin_file_suffix=mixin.json
mixin_refmap_suffix=refmap-mixin.json

# github information
github_project=SrRapero720/waterframes