# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=6

#neogradle.subsystems.parchment.minecraftVersion=1.20.6
#neogradle.subsystems.parchment.mappingsVersion=2024.05.01

systemProp.file.encoding=utf-8

group=me.srrrapero720

#########################
#### Mod properties ####
#######################
modid=waterframes
modname=WaterFrames
modbrandname=WATERFrAMES
modversion=2.1.22
modauthor=SrRapero720
modcredits=Models by FabiAcr and J-RAP. Textures by Kotyarendj
modlicense=All-Rights-Reserved
mod_description=Display custom video and pictures in your world.

####################
#### Mod pages ####
##################
curseforgeid=834607
modrinthid=eBzFuVTM
versiontype=release

#####################
#### Enviroment ####
###################
modloader=NEOFORGE
mcversion=1.21.1
mcrange=[1.21.1,1.21.2)
fgversion=21.1.209
fgloaderrange=[2,)
fgrange=[21.1.200,)
respack_version=48

#######################
#### Dependencies ####
#####################
watermediaversion=2.1.34
watermediarange=[2.1.34,2.2)

creativecoreversion=7002671
creativecorerange=[2.13.13,2.14)

watervisionversion=7043267
watervisionrange=[0.1,0.2)

#######################
#### Placeholders ####
#####################
mixin_file_suffix=mixin.json
mixin_refmap_suffix=refmap-mixin.json

# github information
github_project=SrRapero720/waterframes