modLoader="javafml"
loaderVersion="${fgloaderrange}"
issueTrackerURL="https://github.com/${github_project}/issues"
logoFile="pack.png"
license="${modlicense}"

[[mods]]
	modId="${modid}"
	version="${modversion}"
	displayName="${modname}"
	displayTest="MATCH_VERSION"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/waterframes"
	credits="${modcredits}"
	authors="${modauthor}"
	logoFile="pack.png"
	side="BOTH"
	description='''${mod_description}'''

[[mixins]]
	config="$modid.$mixin_file_suffix"

[[accessTransformers]]
	file="META-INF/accesstransformer.cfg"

[[dependencies.${modid}]]
	modId="neoforge"
	type="required"
	versionRange="${fgrange}"
	ordering="NONE"
	side="BOTH"

[[dependencies.${modid}]]
	modId="creativecore"
	type="required"
	ordering="AFTER"
	side="BOTH"
	versionRange="${creativecorerange}"

[[dependencies.${modid}]]
	modId="watermedia"
	type="required"
	ordering="AFTER"
	side="CLIENT"
	versionRange="${watermediarange}"

[[dependencies.${modid}]]
	modId="mr_stellarity"
	type="incompatible"
	reason="breaks the picture rendering, cropping it and rotating it"
	ordering="NONE"
	side="CLIENT"

[[dependencies.${modid}]]
	modId="stellarity"
	type="incompatible"
	reason="breaks the picture rendering, cropping it and rotating it"
	ordering="NONE"
	side="CLIENT"