package me.srrapero720.waterframes;

public class DisplayConstants {
    static final String[] WHITELIST = new String[] {
            "imgur.com",
            "gyazo.com",
            "prntscr.com",
            "tinypic.com",
            "puu.sh",
            "pinimg.com",
            "photobucket.com",
            "staticflickr.com",
            "flic.kr",
            "tenor.co",
            "gfycat.com",
            "giphy.com",
            "gph.is",
            "gifbin.com",
            "i.redd.it",
            "media.tumblr.com",
            "twimg.com",
            "discordapp.com",
            "images.discordapp.net",
            "discord.com",
            "githubusercontent.com",
            "googleusercontent.com",
            "googleapis.com",
            "wikimedia.org",
            "ytimg.com",
            "youtube.com",
            "youtu.be",
            "twitch.com",
            "twitter.com",
            "soundcloud.com",
            "kick.com",
            "srrapero720.me",
            "youtu.be",
            "fbcdn.net",
            "drive.google.com",
    };
}
